import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardCandidateViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'candidate'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    // allCandidates view fields
    allCandidatesName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'name',
        fieldName: 'name',
        position: 0,
        isVisible: true,
        size: 150,
      },
    }),
    allCandidatesStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 1,
        isVisible: true,
        size: 150,
      },
    }),
    allCandidatesCurrentTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'currentTitle',
        fieldName: 'currentTitle',
        position: 2,
        isVisible: true,
        size: 150,
      },
    }),
    allCandidatesCurrentCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'currentCompany',
        fieldName: 'currentCompany',
        position: 3,
        isVisible: true,
        size: 150,
      },
    }),
    allCandidatesJob: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'job',
        fieldName: 'job',
        position: 4,
        isVisible: true,
        size: 150,
      },
    }),
    allCandidatesCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'allCandidates',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),

    // byStatus (kanban) view fields
    byStatusName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'byStatus',
        viewFieldName: 'name',
        fieldName: 'name',
        position: 0,
        isVisible: true,
        size: 150,
      },
    }),
    byStatusCurrentTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'byStatus',
        viewFieldName: 'currentTitle',
        fieldName: 'currentTitle',
        position: 1,
        isVisible: true,
        size: 150,
      },
    }),
    byStatusCurrentCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'byStatus',
        viewFieldName: 'currentCompany',
        fieldName: 'currentCompany',
        position: 2,
        isVisible: true,
        size: 150,
      },
    }),
    byStatusJob: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'byStatus',
        viewFieldName: 'job',
        fieldName: 'job',
        position: 3,
        isVisible: true,
        size: 150,
      },
    }),

    // candidateRecordPageFields view fields
    candidateRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsEmail: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'email',
        fieldName: 'email',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsPhone: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'phone',
        fieldName: 'phone',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsJob: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'job',
        fieldName: 'job',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsCurrentTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'currentTitle',
        fieldName: 'currentTitle',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    candidateRecordPageFieldsCurrentCompany:
      createStandardViewFieldFlatMetadata({
        ...args,
        objectName: 'candidate',
        context: {
          viewName: 'candidateRecordPageFields',
          viewFieldName: 'currentCompany',
          fieldName: 'currentCompany',
          position: 1,
          isVisible: true,
          size: 150,
          viewFieldGroupName: 'additional',
        },
      }),
    candidateRecordPageFieldsLinkedInUrl: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'linkedInUrl',
        fieldName: 'linkedInUrl',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    candidateRecordPageFieldsSource: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'source',
        fieldName: 'source',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    candidateRecordPageFieldsResumeUrl: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'resumeUrl',
        fieldName: 'resumeUrl',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    candidateRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    candidateRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    candidateRecordPageFieldsUpdatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'updatedAt',
        fieldName: 'updatedAt',
        position: 2,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    candidateRecordPageFieldsUpdatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'updatedBy',
        fieldName: 'updatedBy',
        position: 3,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    candidateRecordPageFieldsFavorites: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'favorites',
        fieldName: 'favorites',
        position: 5,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsTaskTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'taskTargets',
        fieldName: 'taskTargets',
        position: 6,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsNoteTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'noteTargets',
        fieldName: 'noteTargets',
        position: 7,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsAttachments: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'candidate',
      context: {
        viewName: 'candidateRecordPageFields',
        viewFieldName: 'attachments',
        fieldName: 'attachments',
        position: 8,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    candidateRecordPageFieldsTimelineActivities:
      createStandardViewFieldFlatMetadata({
        ...args,
        objectName: 'candidate',
        context: {
          viewName: 'candidateRecordPageFields',
          viewFieldName: 'timelineActivities',
          fieldName: 'timelineActivities',
          position: 9,
          isVisible: false,
          size: 150,
          viewFieldGroupName: 'general',
        },
      }),
  };
};
