import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardJobViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'job'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    // allJobs view fields
    allJobsTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        size: 200,
      },
    }),
    allJobsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 1,
        isVisible: true,
        size: 150,
      },
    }),
    allJobsLocation: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'location',
        fieldName: 'location',
        position: 2,
        isVisible: true,
        size: 150,
      },
    }),
    allJobsDepartment: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'department',
        fieldName: 'department',
        position: 3,
        isVisible: true,
        size: 150,
      },
    }),
    allJobsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 4,
        isVisible: true,
        size: 150,
      },
    }),
    allJobsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'allJobs',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),

    // jobRecordPageFields view fields
    jobRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsLocation: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'location',
        fieldName: 'location',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsCandidates: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'candidates',
        fieldName: 'candidates',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsDepartment: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'department',
        fieldName: 'department',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    jobRecordPageFieldsSalaryRange: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'salaryRange',
        fieldName: 'salaryRange',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'additional',
      },
    }),
    jobRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    jobRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    jobRecordPageFieldsUpdatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'updatedAt',
        fieldName: 'updatedAt',
        position: 2,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    jobRecordPageFieldsUpdatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'updatedBy',
        fieldName: 'updatedBy',
        position: 3,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'other',
      },
    }),
    jobRecordPageFieldsFavorites: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'favorites',
        fieldName: 'favorites',
        position: 4,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsTaskTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'taskTargets',
        fieldName: 'taskTargets',
        position: 5,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsNoteTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'noteTargets',
        fieldName: 'noteTargets',
        position: 6,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsAttachments: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'attachments',
        fieldName: 'attachments',
        position: 7,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
    jobRecordPageFieldsTimelineActivities: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'job',
      context: {
        viewName: 'jobRecordPageFields',
        viewFieldName: 'timelineActivities',
        fieldName: 'timelineActivities',
        position: 8,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'general',
      },
    }),
  };
};
